import { describe, it, expect } from "vitest";
import { readFileSync, writeFileSync, existsSync, mkdirSync, statSync } from "fs";
import { resolve, dirname } from "path";
import { tmpdir } from "os";

// Guarantees public/sitemap.xml contains a <loc> entry for every active
// Shopify product handle. The sitemap is regenerated by scripts/generate-sitemap.ts
// in the predev/prebuild hooks, so a mismatch means a deploy went out with
// stale URLs (e.g. renamed bundle handles missing from the sitemap).

const SHOPIFY_DOMAIN = "plantly-website-cms-fyvdr.myshopify.com";
const SHOPIFY_TOKEN = "589b067e548fcf74b63923620569cb4b";
const SHOPIFY_API_VERSION = "2025-07";

// Cache Shopify handles on disk so repeated test runs (watch mode, CI reruns)
// don't re-hit the Storefront API. Override TTL via SHOPIFY_HANDLE_CACHE_TTL_MS,
// bypass entirely with SHOPIFY_HANDLE_CACHE=0.
const CACHE_PATH = resolve(tmpdir(), "plaently-shopify-handles.cache.json");
const CACHE_TTL_MS = Number(process.env.SHOPIFY_HANDLE_CACHE_TTL_MS ?? 10 * 60 * 1000);
const CACHE_ENABLED = process.env.SHOPIFY_HANDLE_CACHE !== "0";

function readCache(): string[] | null {
  if (!CACHE_ENABLED || !existsSync(CACHE_PATH)) return null;
  try {
    const age = Date.now() - statSync(CACHE_PATH).mtimeMs;
    if (age > CACHE_TTL_MS) return null;
    const parsed = JSON.parse(readFileSync(CACHE_PATH, "utf-8"));
    return Array.isArray(parsed?.handles) ? parsed.handles : null;
  } catch {
    return null;
  }
}

function writeCache(handles: string[]) {
  if (!CACHE_ENABLED) return;
  try {
    mkdirSync(dirname(CACHE_PATH), { recursive: true });
    writeFileSync(CACHE_PATH, JSON.stringify({ handles, savedAt: Date.now() }));
  } catch {
    // best-effort; cache failure shouldn't break tests
  }
}

async function fetchShopifyHandles(): Promise<string[]> {
  const cached = readCache();
  if (cached) return cached;

  const query = `{ products(first: 100) { edges { node { handle } } } }`;
  const res = await fetch(
    `https://${SHOPIFY_DOMAIN}/api/${SHOPIFY_API_VERSION}/graphql.json`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Storefront-Access-Token": SHOPIFY_TOKEN,
      },
      body: JSON.stringify({ query }),
    },
  );
  if (!res.ok) throw new Error(`Shopify HTTP ${res.status}`);
  const json = (await res.json()) as {
    data?: { products?: { edges: Array<{ node: { handle: string } }> } };
  };
  const handles = (json.data?.products?.edges ?? []).map((e) => e.node.handle);
  writeCache(handles);
  return handles;
}

describe("sitemap.xml ↔ Shopify handle sync", () => {
  it("includes /product/<handle> for every live Shopify product", async () => {
    let handles: string[];
    try {
      handles = await fetchShopifyHandles();
    } catch (err) {
      // Don't fail CI if Shopify is briefly unreachable — only fail on real drift.
      console.warn("Skipping sitemap sync check: Shopify unreachable", err);
      return;
    }

    expect(handles.length).toBeGreaterThan(0);

    const sitemap = readFileSync(resolve("public/sitemap.xml"), "utf-8");
    const missing = handles.filter(
      (h) => !sitemap.includes(`<loc>https://plaently.com/product/${h}</loc>`),
    );

    expect(
      missing,
      `sitemap.xml is missing these Shopify handles — run \`npm run dev\` or \`npm run build\` to regenerate:\n  ${missing.join("\n  ")}`,
    ).toEqual([]);
  }, 15_000);
});