import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { resolve } from "path";

// Guarantees public/sitemap.xml contains a <loc> entry for every active
// Shopify product handle. The sitemap is regenerated by scripts/generate-sitemap.ts
// in the predev/prebuild hooks, so a mismatch means a deploy went out with
// stale URLs (e.g. renamed bundle handles missing from the sitemap).

const SHOPIFY_DOMAIN = "plantly-website-cms-fyvdr.myshopify.com";
const SHOPIFY_TOKEN = "589b067e548fcf74b63923620569cb4b";
const SHOPIFY_API_VERSION = "2025-07";

async function fetchShopifyHandles(): Promise<string[]> {
  const query = `{ products(first: 100) { edges { node { handle } } } }`;
  const res = await fetch(
    `https://${SHOPIFY_DOMAIN}/api/${SHOPIFY_API_VERSION}/graphql.json`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Storefront-Access-Token": SHOPIFY_TOKEN,
      },
      body: JSON.stringify({ query }),
    },
  );
  if (!res.ok) throw new Error(`Shopify HTTP ${res.status}`);
  const json = (await res.json()) as {
    data?: { products?: { edges: Array<{ node: { handle: string } }> } };
  };
  return (json.data?.products?.edges ?? []).map((e) => e.node.handle);
}

describe("sitemap.xml ↔ Shopify handle sync", () => {
  it("includes /product/<handle> for every live Shopify product", async () => {
    let handles: string[];
    try {
      handles = await fetchShopifyHandles();
    } catch (err) {
      // Don't fail CI if Shopify is briefly unreachable — only fail on real drift.
      console.warn("Skipping sitemap sync check: Shopify unreachable", err);
      return;
    }

    expect(handles.length).toBeGreaterThan(0);

    const sitemap = readFileSync(resolve("public/sitemap.xml"), "utf-8");
    const missing = handles.filter(
      (h) => !sitemap.includes(`<loc>https://plaently.com/product/${h}</loc>`),
    );

    expect(
      missing,
      `sitemap.xml is missing these Shopify handles — run \`npm run dev\` or \`npm run build\` to regenerate:\n  ${missing.join("\n  ")}`,
    ).toEqual([]);
  }, 15_000);
});