/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FraktRouteImport } from './routes/frakt'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as KopsvillkorRouteImport } from './routes/kopsvillkor'
import { Route as LifestyleRouteImport } from './routes/lifestyle'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as NyttigSnabbmatRouteImport } from './routes/nyttig-snabbmat'
import { Route as PlantbaseradeMaltiderRouteImport } from './routes/plantbaserade-maltider'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProteinkopparRouteImport } from './routes/proteinkoppar'
import { Route as ProteinrikaMaltiderRouteImport } from './routes/proteinrika-maltider'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBundlesRouteImport } from './routes/admin.bundles'
import { Route as AdminDiscountsRouteImport } from './routes/admin.discounts'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiContactReplyEmailRouteImport } from './routes/api/contact-reply-email'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as ProductsSlugRouteImport } from './routes/products_.$slug'
import { Route as Char91DotlovableChar93OauthConsentRouteImport } from './routes/[.lovable]/oauth/consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicStarterOfferEmailRouteImport } from './routes/api/public/starter-offer-email'
import { Route as BlogCategorySlugRouteImport } from './routes/blog_.category.$slug'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FraktRoute = FraktRouteImport.update({
  id: '/frakt',
  path: '/frakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const KopsvillkorRoute = KopsvillkorRouteImport.update({
  id: '/kopsvillkor',
  path: '/kopsvillkor',
  getParentRoute: () => rootRouteImport,
} as any)
const LifestyleRoute = LifestyleRouteImport.update({
  id: '/lifestyle',
  path: '/lifestyle',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const NyttigSnabbmatRoute = NyttigSnabbmatRouteImport.update({
  id: '/nyttig-snabbmat',
  path: '/nyttig-snabbmat',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantbaseradeMaltiderRoute = PlantbaseradeMaltiderRouteImport.update({
  id: '/plantbaserade-maltider',
  path: '/plantbaserade-maltider',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProteinkopparRoute = ProteinkopparRouteImport.update({
  id: '/proteinkoppar',
  path: '/proteinkoppar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProteinrikaMaltiderRoute = ProteinrikaMaltiderRouteImport.update({
  id: '/proteinrika-maltider',
  path: '/proteinrika-maltider',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBundlesRoute = AdminBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactReplyEmailRoute = ApiContactReplyEmailRouteImport.update({
  id: '/api/contact-reply-email',
  path: '/api/contact-reply-email',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products_/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotlovableChar93OauthConsentRoute =
  Char91DotlovableChar93OauthConsentRouteImport.update({
    id: '/.lovable/oauth/consent',
    path: '/.lovable/oauth/consent',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStarterOfferEmailRoute =
  ApiPublicStarterOfferEmailRouteImport.update({
    id: '/api/public/starter-offer-email',
    path: '/api/public/starter-offer-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog_/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/frakt': typeof FraktRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kopsvillkor': typeof KopsvillkorRoute
  '/lifestyle': typeof LifestyleRoute
  '/mcp': typeof McpRoute
  '/nutrition': typeof NutritionRoute
  '/nyttig-snabbmat': typeof NyttigSnabbmatRoute
  '/plantbaserade-maltider': typeof PlantbaseradeMaltiderRoute
  '/products': typeof ProductsRoute
  '/proteinkoppar': typeof ProteinkopparRoute
  '/proteinrika-maltider': typeof ProteinrikaMaltiderRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact-reply-email': typeof ApiContactReplyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof Char91DotlovableChar93OauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/starter-offer-email': typeof ApiPublicStarterOfferEmailRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/frakt': typeof FraktRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kopsvillkor': typeof KopsvillkorRoute
  '/lifestyle': typeof LifestyleRoute
  '/mcp': typeof McpRoute
  '/nutrition': typeof NutritionRoute
  '/nyttig-snabbmat': typeof NyttigSnabbmatRoute
  '/plantbaserade-maltider': typeof PlantbaseradeMaltiderRoute
  '/products': typeof ProductsRoute
  '/proteinkoppar': typeof ProteinkopparRoute
  '/proteinrika-maltider': typeof ProteinrikaMaltiderRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact-reply-email': typeof ApiContactReplyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof Char91DotlovableChar93OauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/starter-offer-email': typeof ApiPublicStarterOfferEmailRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/frakt': typeof FraktRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kopsvillkor': typeof KopsvillkorRoute
  '/lifestyle': typeof LifestyleRoute
  '/mcp': typeof McpRoute
  '/nutrition': typeof NutritionRoute
  '/nyttig-snabbmat': typeof NyttigSnabbmatRoute
  '/plantbaserade-maltider': typeof PlantbaseradeMaltiderRoute
  '/products': typeof ProductsRoute
  '/proteinkoppar': typeof ProteinkopparRoute
  '/proteinrika-maltider': typeof ProteinrikaMaltiderRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact-reply-email': typeof ApiContactReplyEmailRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/products_/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof Char91DotlovableChar93OauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/starter-offer-email': typeof ApiPublicStarterOfferEmailRoute
  '/blog_/category/$slug': typeof BlogCategorySlugRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/frakt'
    | '/integritetspolicy'
    | '/kopsvillkor'
    | '/lifestyle'
    | '/mcp'
    | '/nutrition'
    | '/nyttig-snabbmat'
    | '/plantbaserade-maltider'
    | '/products'
    | '/proteinkoppar'
    | '/proteinrika-maltider'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/blog'
    | '/admin/bundles'
    | '/admin/discounts'
    | '/admin/faqs'
    | '/admin/hero'
    | '/admin/messages'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin/testimonials'
    | '/admin/login'
    | '/api/chat'
    | '/api/contact-reply-email'
    | '/blog/$slug'
    | '/product/$handle'
    | '/products/$slug'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/starter-offer-email'
    | '/blog/category/$slug'
    | '/lovable/email/events'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/frakt'
    | '/integritetspolicy'
    | '/kopsvillkor'
    | '/lifestyle'
    | '/mcp'
    | '/nutrition'
    | '/nyttig-snabbmat'
    | '/plantbaserade-maltider'
    | '/products'
    | '/proteinkoppar'
    | '/proteinrika-maltider'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/blog'
    | '/admin/bundles'
    | '/admin/discounts'
    | '/admin/faqs'
    | '/admin/hero'
    | '/admin/messages'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin/testimonials'
    | '/admin/login'
    | '/api/chat'
    | '/api/contact-reply-email'
    | '/blog/$slug'
    | '/product/$handle'
    | '/products/$slug'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/starter-offer-email'
    | '/blog/category/$slug'
    | '/lovable/email/events'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/frakt'
    | '/integritetspolicy'
    | '/kopsvillkor'
    | '/lifestyle'
    | '/mcp'
    | '/nutrition'
    | '/nyttig-snabbmat'
    | '/plantbaserade-maltider'
    | '/products'
    | '/proteinkoppar'
    | '/proteinrika-maltider'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/blog'
    | '/admin/bundles'
    | '/admin/discounts'
    | '/admin/faqs'
    | '/admin/hero'
    | '/admin/messages'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin/testimonials'
    | '/admin_/login'
    | '/api/chat'
    | '/api/contact-reply-email'
    | '/blog_/$slug'
    | '/product/$handle'
    | '/products_/$slug'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/starter-offer-email'
    | '/blog_/category/$slug'
    | '/lovable/email/events'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FraktRoute: typeof FraktRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  KopsvillkorRoute: typeof KopsvillkorRoute
  LifestyleRoute: typeof LifestyleRoute
  McpRoute: typeof McpRoute
  NutritionRoute: typeof NutritionRoute
  NyttigSnabbmatRoute: typeof NyttigSnabbmatRoute
  PlantbaseradeMaltiderRoute: typeof PlantbaseradeMaltiderRoute
  ProductsRoute: typeof ProductsRoute
  ProteinkopparRoute: typeof ProteinkopparRoute
  ProteinrikaMaltiderRoute: typeof ProteinrikaMaltiderRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiContactReplyEmailRoute: typeof ApiContactReplyEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  Char91DotlovableChar93OauthConsentRoute: typeof Char91DotlovableChar93OauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicStarterOfferEmailRoute: typeof ApiPublicStarterOfferEmailRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frakt': {
      id: '/frakt'
      path: '/frakt'
      fullPath: '/frakt'
      preLoaderRoute: typeof FraktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopsvillkor': {
      id: '/kopsvillkor'
      path: '/kopsvillkor'
      fullPath: '/kopsvillkor'
      preLoaderRoute: typeof KopsvillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifestyle': {
      id: '/lifestyle'
      path: '/lifestyle'
      fullPath: '/lifestyle'
      preLoaderRoute: typeof LifestyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nyttig-snabbmat': {
      id: '/nyttig-snabbmat'
      path: '/nyttig-snabbmat'
      fullPath: '/nyttig-snabbmat'
      preLoaderRoute: typeof NyttigSnabbmatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantbaserade-maltider': {
      id: '/plantbaserade-maltider'
      path: '/plantbaserade-maltider'
      fullPath: '/plantbaserade-maltider'
      preLoaderRoute: typeof PlantbaseradeMaltiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proteinkoppar': {
      id: '/proteinkoppar'
      path: '/proteinkoppar'
      fullPath: '/proteinkoppar'
      preLoaderRoute: typeof ProteinkopparRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proteinrika-maltider': {
      id: '/proteinrika-maltider'
      path: '/proteinrika-maltider'
      fullPath: '/proteinrika-maltider'
      preLoaderRoute: typeof ProteinrikaMaltiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bundles': {
      id: '/admin/bundles'
      path: '/bundles'
      fullPath: '/admin/bundles'
      preLoaderRoute: typeof AdminBundlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact-reply-email': {
      id: '/api/contact-reply-email'
      path: '/api/contact-reply-email'
      fullPath: '/api/contact-reply-email'
      preLoaderRoute: typeof ApiContactReplyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$slug': {
      id: '/products_/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof Char91DotlovableChar93OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/starter-offer-email': {
      id: '/api/public/starter-offer-email'
      path: '/api/public/starter-offer-email'
      fullPath: '/api/public/starter-offer-email'
      preLoaderRoute: typeof ApiPublicStarterOfferEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/category/$slug': {
      id: '/blog_/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBundlesRoute: typeof AdminBundlesRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminBundlesRoute: AdminBundlesRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FraktRoute: FraktRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  KopsvillkorRoute: KopsvillkorRoute,
  LifestyleRoute: LifestyleRoute,
  McpRoute: McpRoute,
  NutritionRoute: NutritionRoute,
  NyttigSnabbmatRoute: NyttigSnabbmatRoute,
  PlantbaseradeMaltiderRoute: PlantbaseradeMaltiderRoute,
  ProductsRoute: ProductsRoute,
  ProteinkopparRoute: ProteinkopparRoute,
  ProteinrikaMaltiderRoute: ProteinrikaMaltiderRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiChatRoute: ApiChatRoute,
  ApiContactReplyEmailRoute: ApiContactReplyEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProductHandleRoute: ProductHandleRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  Char91DotlovableChar93OauthConsentRoute:
    Char91DotlovableChar93OauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicStarterOfferEmailRoute: ApiPublicStarterOfferEmailRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
