// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Sign in to this app to use this tool." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List PL\xC4NTLY products from the CMS with name, slug, price, protein and publish state.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Optional case-insensitive name filter."),
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of products to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("products").select("id,name,slug,price,protein,calories,sku,is_published,sort_order").order("sort_order", { ascending: true }).limit(limit ?? 25);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_blog_posts_default = defineTool2({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List blog posts from the CMS, optionally filtered by language, category or publish state.",
  inputSchema: {
    language: z2.enum(["sv", "en"]).optional().describe("Filter by post language."),
    category: z2.string().trim().min(1).optional().describe("Filter by category slug."),
    published: z2.boolean().optional().describe("Filter by publish state."),
    limit: z2.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ language, category, published, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("blog_posts").select("id,title,slug,excerpt,category,language,is_published,published_at,updated_at").order("published_at", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (language) query = query.eq("language", language);
    if (category) query = query.eq("category", category);
    if (typeof published === "boolean") query = query.eq("is_published", published);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_blog_post_default = defineTool3({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch the full content of a single blog post by its slug.",
  inputSchema: { slug: z3.string().trim().min(1).describe("The blog post slug.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("blog_posts").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No blog post found with slug "${slug}".` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/create-blog-post.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_blog_post_default = defineTool4({
  name: "create_blog_post",
  title: "Create blog post",
  description: "Create a new blog post in the CMS. Created as a draft unless publish is set to true.",
  inputSchema: {
    title: z4.string().trim().min(1),
    slug: z4.string().trim().min(1).regex(/^[a-z0-9-]+$/, "Slug must be lowercase letters, numbers and hyphens."),
    content: z4.string().trim().min(1).describe("Post body (HTML or markdown)."),
    excerpt: z4.string().trim().optional(),
    category: z4.string().trim().optional(),
    language: z4.enum(["sv", "en"]).default("sv"),
    publish: z4.boolean().default(false).describe("Publish immediately instead of saving as a draft.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, slug, content, excerpt, category, language, publish }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("blog_posts").insert({
      title,
      slug,
      content,
      excerpt: excerpt ?? null,
      category: category ?? null,
      language: language ?? "sv",
      is_published: publish ?? false,
      published_at: publish ? (/* @__PURE__ */ new Date()).toISOString() : null
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-faqs.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_faqs_default = defineTool5({
  name: "list_faqs",
  title: "List FAQs",
  description: "List FAQ entries (English and Swedish) from the CMS.",
  inputSchema: {
    publishedOnly: z5.boolean().default(true).describe("Only return published FAQs."),
    limit: z5.number().int().min(1).max(100).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ publishedOnly, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("faqs").select("id,question,answer,question_sv,answer_sv,is_published,sort_order").order("sort_order", { ascending: true }).limit(limit ?? 50);
    if (publishedOnly !== false) query = query.eq("is_published", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { faqs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-contact-messages.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_contact_messages_default = defineTool6({
  name: "list_contact_messages",
  title: "List contact messages",
  description: "List customer messages submitted through the contact form (admin access only).",
  inputSchema: {
    unreadOnly: z6.boolean().default(false).describe("Only return messages that have not been marked as read."),
    limit: z6.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unreadOnly, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contact_submissions").select("id,name,email,message,is_read,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (unreadOnly) query = query.eq("is_read", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fpwwjbevjhxbggtkaabc";
var mcp_default = defineMcp({
  name: "plaently-protein-fast-food",
  title: "Pl\xE4ntly Protein Fast Food",
  version: "0.1.0",
  instructions: "Tools for the PL\xC4NTLY plant-based protein meals site. Read products, FAQs and blog posts from the CMS, draft or publish new blog posts, and review customer contact messages. All tools act as the signed-in PL\xC4NTLY user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_products_default,
    list_faqs_default,
    list_blog_posts_default,
    get_blog_post_default,
    create_blog_post_default,
    list_contact_messages_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
